spring.application.name=agenda-api

// Configurações do servidor OPENAPI
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=abcdefghijklmnopqrstuvwxyzksdadd
jwt.expiration-ms=86400000

# --- E-mail (JavaMailSender) ---
spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=1e24373ab228cb
spring.mail.password=44a0fc7f278408
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mail.from=${MAIL_FROM:no-reply@reifbeautystudio.com}

app.frontend-url=${FRONTEND_URL:http://localhost:3000}

app.reminder-hours-before=3
app.reminder-check-interval-ms=60000